# Generated by Django 4.2 on 2023-05-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_item_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
